---
- hosts: webservers 
  become: True
  tasks:
    - name: Install packages
      yum:
        name: "httpd"
        state: "present"
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    - name: Start http server
      service:
        name: httpd
        state: started
        enabled: True
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    - name: Install packages
      apt:
        name: "apache2"
        state: "present"
      when: ansible_distribution == "Ubuntu"
    - name: Start Apache server
      service:
        name: apache2
        state: started
        enabled: True
      when: ansible_distribution == "Ubuntu"
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
